wr-132:  Add date-fns package for dates
BinaryStudioAcademy/bsa-2023-writorium pull request #143
Opened 2023-09-04 14:31 UTC by hnoievets

- [x] Add [date-fns](https://date-fns.org/) package to shared folder
- [x]  Provide helpers for date formatting
- [x]  Replace places throughout the code to use date-fns helpers to manage dates shape

2023-09-04 14:47 UTC, WilhelmWesser requested changes

2023-09-04 14:47 UTC, WilhelmWesser commented on shared/src/libs/enums/date-pattern.emun.ts
> +const DatePattern = {
typo in file name

2023-09-04 14:51 UTC, hnoievets commented on shared/src/libs/enums/date-pattern.emun.ts
> +const DatePattern = {
Thanks

2023-09-04 17:43 UTC, andanf-e requested changes

2023-09-04 17:43 UTC, andanf-e commented on shared/src/libs/enums/date-pattern.enum.ts
> +} as const;
```suggestion
const DateFormat = {
  DAY_SHORT_MONTH: 'd MMM',
} as const;
```

2023-09-04 17:43 UTC, andanf-e commented on shared/src/libs/helpers/format-date/format-date.helper.ts
> +  return format(new Date(isoString), pattern, options);
```suggestion
const getFormattedDate = (date: string, format: ValueOf<typeof DateFormat>): string => {
  return format(new Date(date), format);
```

2023-09-05 09:31 UTC, andanf-e approved these changes

2023-09-05 09:33 UTC, WilhelmWesser approved these changes

2023-09-05 09:42 UTC, merged