wr-139: Add responsive for Sign In/Up pages
BinaryStudioAcademy/bsa-2023-writorium pull request #144
Opened 2023-09-04 15:33 UTC by AnastasiaR2

Added responsiveness for Auth pages. On the narrow screens, the right side with bg is hidden. Currently, the title is not responsive, so I disabled the font-size property to make a second screenshot. But I checked with the logo from Iryna's task, and it's working as expected.

![image_2023-09-04_12-51-02](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/85576361/cb8dd15b-6505-42ff-b945-c6e57130ee40)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/85576361/e81b5298-9f69-4365-bb3f-c7bc99b42f5d)
![image_2023-09-04_12-51-56](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/85576361/710fd694-0186-453d-bbf7-3bf9da184916)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/85576361/20aa7c42-7b8a-41c1-bce9-19792595fe83)

2023-09-04 18:10 UTC, WilhelmWesser submitted a review, later dismissed

2023-09-04 18:34 UTC, andanf-e reviewed
Please also check how landing page looks, and I believe bg images with typewriter should not focus on wooden table

2023-09-05 08:21 UTC, andanf-e requested changes

2023-09-05 08:21 UTC, andanf-e commented on frontend/src/pages/landing/landing.tsx
> +        className={`${styles.parallaxImg} ${styles.bgLetters}`}
```suggestion
        className={getValidClassNames(styles.parallaxImg, styles.bgLetters)}
```

2023-09-05 09:27 UTC, andanf-e approved these changes

2023-09-05 09:33 UTC, WilhelmWesser approved these changes

2023-09-05 09:37 UTC, merged