wr-129: implement sign in with google
BinaryStudioAcademy/bsa-2023-writorium pull request #145
Opened 2023-09-04 17:17 UTC by canterbery

- Add Sign In with Google button on Sign In page
-  sign in with google should open default Google OAuth window
-  Upon successful Google login - make BE request to sign user in with our credentials

2023-09-04 18:03 UTC, WilhelmWesser approved these changes, later dismissed

2023-09-04 19:04 UTC, andanf-e requested changes

2023-09-04 19:04 UTC, andanf-e commented on backend/.env.example
> +CLIENT_SECRET=""
To make it more clear
```suggestion
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
```

2023-09-04 19:04 UTC, andanf-e commented on frontend/src/pages/auth/components/sign-in-form/styles.module.scss
> +  font-family: Montserat, sans-serif;
Let's use Raleway (Montserrat is used on design, but 4 fonts I guess is to much :c )

2023-09-04 19:04 UTC, andanf-e commented on frontend/src/pages/auth/components/auth-sign-in-button/auth-sign-in-button.tsx
> +    <Button {...properties} className={styles.authSignInButton} type="submit" />
Please pass properties explicitly

2023-09-04 19:04 UTC, andanf-e commented on frontend/src/pages/auth/auth.tsx
> +  const handleGoogleLogin = useCallback(() => login(), [login]);
Can't we pass this handler as it's returned from hook?
```suggestion
  const handleGoogleLogin = useGoogleLogin({
    onSuccess: ({ code }) => {
      void dispatch(authActions.loginWithGoogle({ code }));
    },

    flow: 'auth-code',
  });
```

2023-09-04 19:04 UTC, andanf-e commented on backend/src/packages/auth/auth.controller.ts
> +  private async LoginWithGoogle(
```suggestion
  private async loginWithGoogle(
```

2023-09-05 05:27 UTC, PablloZz commented on frontend/src/pages/auth/components/auth-sign-in-button/auth-sign-in-button.tsx
> +    <Button {...properties} className={styles.authSignInButton} type="submit" />
There is an enum ButtonType for buttons types

2023-09-05 05:30 UTC, PablloZz commented on frontend/src/pages/auth/components/auth-sign-in-button/styles.module.scss
> +  color: #2e453b;
Please use variable for the color here

2023-09-05 06:46 UTC, andanf-e commented on backend/src/libs/packages/config/config.package.ts
> +        GOOGLE_CLIENT_SECRET: {
Here we can leave it as it is -- as we already grouped them under `GOOGLE_AUTH`
```suggestion
      GOOGLE_AUTH: {
        CLIENT_ID: {
          doc: 'Google Auth api client id',
          format: String,
          env: 'GOOGLE_CLIENT_ID',
          default: null,
        },
        CLIENT_SECRET: {
```

2023-09-05 07:00 UTC, andanf-e approved these changes, later dismissed

2023-09-05 09:34 UTC, WilhelmWesser submitted a review, later dismissed

2023-09-05 11:08 UTC, WilhelmWesser approved these changes

2023-09-05 11:11 UTC, andanf-e approved these changes

2023-09-05 11:14 UTC, merged