wr-159: Unify loaders implementation
BinaryStudioAcademy/bsa-2023-writorium pull request #196
Opened 2023-09-10 20:12 UTC by IrynaK-a

2023-09-10 20:27 UTC, WilhelmWesser submitted a review, later dismissed

2023-09-11 07:11 UTC, andanf-e requested changes

2023-09-11 07:11 UTC, andanf-e commented on frontend/src/libs/components/app/app.tsx
> +      <Loader isLoading={isLoading} hasOverlay={true} loaderType="circular">
```suggestion
      <Loader isLoading={isLoading} hasOverlay loaderType="circular">
```

2023-09-11 07:11 UTC, andanf-e commented on frontend/src/libs/enums/loader.enum.ts
> +const ILoader = {
Or LoaderType, or everything else, not `ILoader`
```suggestion
const LoaderShape = {
```

2023-09-11 07:11 UTC, andanf-e commented on frontend/src/pages/article/article-page.tsx
> +    <Loader isLoading={isLoading} hasOverlay={true} loaderType="circular">
And if you've created a enum - then why don't you use it?
```suggestion
    <Loader isLoading={isLoading} hasOverlay loaderType="circular">
```

2023-09-11 07:11 UTC, andanf-e commented on frontend/src/libs/components/prompt-generation/libs/components/prompt-card/prompt-card.tsx
> +      <Loader isLoading={isGenerating} hasOverlay={false} loaderType="dots">
And same about enum usage
```suggestion
      <Loader isLoading={isGenerating} loaderType="dots">
```

2023-09-11 07:11 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +  hasOverlay: boolean;
```suggestion
  hasOverlay?: boolean;
```

2023-09-11 07:11 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +  hasOverlay,
```suggestion
  hasOverlay = false,
```

2023-09-11 07:11 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +  };
The only thing different in this map is className passed - just pass it by condition

2023-09-11 07:11 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +  return <>{children}</>;
```suggestion
  return children;
```

2023-09-11 07:11 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +import { type ValueOf } from 'shared/build';
Import it from `~/libs/types/types.js`

2023-09-11 09:35 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +  loaderType: LoaderShape;
If that type is used only here - then let's declare it locally for component properties
```suggestion
  loaderType: 'dots' | 'circular';
```

2023-09-11 13:29 UTC, hnoievets commented on frontend/src/libs/components/loader/loader.tsx
It seems to me that moving the main code out of the if-statement will make this code more readable. If I understand the 'early returning' approach correctly.

2023-09-11 14:27 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +  if (isLoading) {
As Oleg mentioned
Let's invert this check with early return - 
Like
```
if (!isLoading) {
  return children;
}

... all stuff with loaders
```

2023-09-11 14:27 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +        ></div>
As we've restricted `loaderType` value with predefined values - `circular` | `dots`
Let's just bring styling classes with same names and make it easier:
```suggestion

    return (
      <div className={containerClassName}>
        <div className={getValidClassNames(styles[loaderType], className)} />
```

2023-09-11 14:36 UTC, IrynaK-a commented on frontend/src/libs/components/loader/loader.tsx
Yes, it's a good point, thanks.

2023-09-11 15:19 UTC, andanf-e requested changes

2023-09-11 15:19 UTC, andanf-e commented on frontend/src/libs/components/prompt-generation/libs/components/prompt-card/prompt-card.tsx
> +      <Loader isLoading={isGenerating} hasOverlay={false} loaderType="dots">
`hasOverlay` is set to false by default
```suggestion
      <Loader isLoading={isGenerating} loaderType="dots">
```

2023-09-11 19:49 UTC, andanf-e submitted a review, later dismissed

2023-09-12 04:45 UTC, artemmatiushenko1 commented on frontend/src/libs/components/loader/loader.tsx
> +  loaderType: 'dots' | 'circular';
Maybe it would be better to name this prop as just `type`, I guess it’s self explanatory as well when passing it to `Loader` component

2023-09-12 07:12 UTC, WilhelmWesser approved these changes, later dismissed

2023-09-12 07:24 UTC, andanf-e approved these changes, later dismissed

2023-09-12 07:24 UTC, andanf-e commented on frontend/src/pages/article/components/article-form/libs/components/article-cover-upload/article-cover-upload.tsx
>  // @todo: fix import after https://github.com/BinaryStudioAcademy/bsa-2023-writorium/issues/159 is done
Check if this comment could be removed

2023-09-12 08:32 UTC, andanf-e approved these changes

2023-09-12 15:45 UTC, WilhelmWesser approved these changes

2023-09-12 15:48 UTC, merged