Task/wr 190 show real prompt data on article view
BinaryStudioAcademy/bsa-2023-writorium pull request #214
Opened 2023-09-13 12:35 UTC by kovAnya

2023-09-13 13:32 UTC, IrynaK-a commented on frontend/src/pages/article/article-page.tsx
> +          {getArticleStatus === DataStatus.FULFILLED && (
It seems redundant. We've already done this check earlier (Loader and getArticleStatus === DataStatus.REJECTED)

2023-09-13 13:36 UTC, IrynaK-a commented on frontend/src/pages/article/components/article-view/styles.module.scss
> +  margin-left: auto;
You can simplify this: margin: 28px auto 0;

2023-09-13 13:40 UTC, IrynaK-a commented on frontend/src/pages/article/shared-article-page.tsx
> +          {dataStatus === DataStatus.FULFILLED && (
It seems redundant too.

2023-09-13 13:56 UTC, andanf-e requested changes

2023-09-13 13:56 UTC, andanf-e commented on frontend/src/libs/types/tag.type.ts
> +import { type PromptCategory } from 'shared/build/packages/prompts/prompts.js';
```suggestion
import { PromptCategory } from '~/packages/prompts/libs/enums/enums.js';
```

2023-09-13 13:56 UTC, andanf-e commented on frontend/src/pages/article/libs/helpers/get-article-view-tags.helper.ts
> +  if (tags.length > 0) {
```suggestion
  if (tags.length) {
```

2023-09-13 13:56 UTC, andanf-e commented on frontend/src/pages/article/libs/helpers/get-article-view-tags.helper.ts
> +    return tags.filter((tag) => tag.category !== 'genre');
```suggestion
    return tags.filter((tag) => tag.category !== PromptCategory.GENRE);
```

2023-09-13 14:15 UTC, kovAnya commented on frontend/src/libs/types/tag.type.ts
> +import { type PromptCategory } from 'shared/build/packages/prompts/prompts.js';
I've changed path, but kept type declaration, eslint insists on it.

2023-09-13 14:34 UTC, andanf-e approved these changes

2023-09-14 05:57 UTC, nickolay-grechkin approved these changes

2023-09-14 06:11 UTC, merged