wr 232: Add ability for authors to edit and delete their articles directly from the article viewing page
BinaryStudioAcademy/bsa-2023-writorium pull request #240
Opened 2023-09-15 10:38 UTC by PablloZz

![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/84803938/29da83fd-1150-45da-b7a3-f25d9d078a24)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/84803938/74cafc11-abee-46dc-b9be-ea5592544e9b)
 Add ability to edit my articles from the "Feed" tab. Was implemented in @AnastasiaR2 PR.
 Add ability to edit my articles from the article viewing page.
 Add ability to delete my articles from the "Feed" tab. Was implemented in @AnastasiaR2 PR.
 Add ability to delete my articles from the article viewing page.

2023-09-15 10:43 UTC, artemmatiushenko1 commented on frontend/src/pages/article/components/article-view/styles.module.scss
> +  min-width: 30px;
I guess we can just remove `top: 100px;` from `buttonsWrapper`, so each button doesn't shrink in size. Currently the icons look quite large

2023-09-15 14:26 UTC, andanf-e requested changes
And fix issues with package-lock

2023-09-15 14:26 UTC, andanf-e commented on frontend/src/libs/constants/previous-page-index.ts
Should be `previous-page-index.constant`

2023-09-15 14:26 UTC, andanf-e commented on frontend/src/pages/article/components/article-view/article-view.tsx
> +                >
Use common `Link` component,
And please change it on article-card component,
I missed it

2023-09-16 08:13 UTC, andanf-e approved these changes

2023-09-16 18:07 UTC, merged