wr-224: Show latest 5 user articles in user profile
BinaryStudioAcademy/bsa-2023-writorium pull request #242
Opened 2023-09-15 11:46 UTC by kovAnya

2023-09-15 14:32 UTC, andanf-e requested changes

2023-09-15 14:32 UTC, andanf-e commented on frontend/src/pages/profile/components/user-latest-articles/libs/enums/own-articles-config.enum.ts
> +const ownArticlesConfig = {
```suggestion
const ownArticlesPaginationConfig = {
```

2023-09-15 14:32 UTC, andanf-e commented on frontend/src/pages/profile/components/user-latest-articles/user-latest-articles.tsx
> +    getLatest();
```suggestion
  useEffect(() => {
    void dispatch(
      articlesActions.fetchOwn({
        take: ownArticlesConfig.TAKE,
        skip: ownArticlesConfig.SKIP,
      }),
    );
```

2023-09-15 19:44 UTC, andanf-e submitted a review, later dismissed

2023-09-17 14:13 UTC, andanf-e requested changes

2023-09-17 14:13 UTC, andanf-e commented on frontend/src/pages/profile/components/user-latest-articles/user-latest-articles.tsx
> +              }
```suggestion
              to={configureString(
                  AppRoute.ARTICLES_$ID,
                  { id: String(article.id) }
                ) as AppRoute.ARTICLES_$ID
              }
```

2023-09-17 14:13 UTC, andanf-e commented on frontend/src/pages/profile/components/user-latest-articles/user-latest-articles.tsx
> +        to={AppRoute.ARTICLES_MY_ARTICLES as typeof AppRoute.ARTICLES_$ID}
I'm not sure that you need to cast one AppRoute enum to another
```suggestion
        to={AppRoute.ARTICLES_MY_ARTICLES}
```

2023-09-17 15:25 UTC, andanf-e approved these changes

2023-09-17 16:03 UTC, andanf-e reviewed
Please also provide screenshot

2023-09-17 16:14 UTC, kovAnya commented
> Please also provide screenshot

![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/104009473/ce5efaa5-e474-45b7-96c0-905db44944b5)

2023-09-17 20:25 UTC, andanf-e approved these changes, later dismissed

2023-09-17 20:26 UTC, andanf-e reviewed
Maybe let's also add heading like `Your latest articles` to this section

2023-09-18 06:16 UTC, nickolay-grechkin submitted a review, later dismissed

2023-09-18 06:29 UTC, kovAnya commented
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/104009473/d71150f9-78a1-4654-b974-0d564b06993d)

2023-09-18 06:46 UTC, andanf-e approved these changes

2023-09-18 08:46 UTC, WilhelmWesser approved these changes

2023-09-18 08:50 UTC, merged