wr-243: Add save draft button on draft editing page
BinaryStudioAcademy/bsa-2023-writorium pull request #252
Opened 2023-09-17 14:47 UTC by kovAnya

2023-09-17 14:56 UTC, kovAnya commented
I added the Save Draft button to article editing so that if it was a draft, it remains a draft, and if the article was published, then after clicking Save Draft, it goes into a draft. Or should for published articles be unavailable to save as a draft?

2023-09-17 15:31 UTC, andanf-e requested changes

2023-09-17 15:31 UTC, andanf-e commented on frontend/src/pages/article/components/article-form/article-form.tsx
> +      void handleSubmit(handleFunction(submitType))(event_);
```suggestion
```

2023-09-17 15:31 UTC, andanf-e commented on frontend/src/pages/article/components/article-form/article-form.tsx
> +        : handleArticleSubmit;
Let's split handlers explicitly
```suggestion
      if (articleForUpdate) {
        void handleSubmit(handleArticleUpdate(submitType))(event_);
        return;
      }
      
      void handleSubmit(handleArticleSubmit(submitType))(event_);
```

2023-09-17 15:55 UTC, andanf-e approved these changes, later dismissed

2023-09-18 06:18 UTC, nickolay-grechkin submitted a review, later dismissed

2023-09-18 06:43 UTC, andanf-e approved these changes

2023-09-18 08:45 UTC, WilhelmWesser approved these changes

2023-09-18 08:46 UTC, merged