wr-248: redirected to the login page when the token is unavailable
BinaryStudioAcademy/bsa-2023-writorium pull request #268
Opened 2023-09-18 17:08 UTC by IrynaK-a

2023-09-18 19:02 UTC, andanf-e requested changes

2023-09-18 19:02 UTC, andanf-e commented on frontend/src/libs/packages/api/http-api.package.ts
> +        parsedException.message === ExceptionMessage.DO_NOT_HAVE_AUTHORIZATION)
```suggestion
      /** somewhere in constants for this package */
      const UNAUTHORIZED_ACTION_ERRORS = [
        ExceptionMessage.INVALID_TOKEN,
        ExceptionMessage.AUTHORIZATION_HEADER,
        ExceptionMessage.DO_NOT_HAVE_AUTHORIZATION
      ] as const;
      .
      .
      UNAUTHORIZED_ACTION_ERRORS.includes(parsedException.message)
```

2023-09-19 06:31 UTC, andanf-e requested changes

2023-09-19 06:31 UTC, andanf-e commented on frontend/src/libs/packages/api/libs/constants/unauthorized-action-errors.ts
files with constants should have suffix .constant (`unauthorized-action-errors.constant`)

2023-09-19 07:12 UTC, WilhelmWesser approved these changes

2023-09-19 07:54 UTC, andanf-e approved these changes

2023-09-19 07:55 UTC, merged