wr-231: Implement a confirmation dialog for the article deletion feature
BinaryStudioAcademy/bsa-2023-writorium pull request #269
Opened 2023-09-18 17:14 UTC by AnastasiaR2

1. Implemented a confirmation dialog for the article deletion feature
2. Added a success message the article has been successfully deleted.

![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/85576361/37b21c40-84f7-45ca-be1e-82e2c98850a8)

2023-09-18 18:59 UTC, andanf-e requested changes

2023-09-18 18:59 UTC, andanf-e commented on frontend/src/pages/articles/components/article-card/libs/components/popover-buttons-group/popover-buttons-group.tsx
> +  handleDeleteButtonClick: () => void;
Check **A9**
```suggestion
  onDeleteArticle: () => void;
```

2023-09-18 18:59 UTC, andanf-e commented on frontend/src/libs/components/confirm-dialog/confirm-dialog.tsx
Let's better create `ConfirmArticleDeleteDialog` component specific for article pages then you'd have one sophisticated modal for all articles and you'd need to pass only `onDelete` handler, and common `dialog` props

2023-09-19 09:30 UTC, andanf-e requested changes

2023-09-19 09:30 UTC, andanf-e commented on frontend/src/libs/components/components.ts
> +export { ConfirmArticleDeleteDialog } from './confirm-article-delete-dialog/confirm-article-delete-dialog.js';
Let's create separate `components` in `pages` folder and move more specific but reusable components for page there

2023-09-19 09:30 UTC, andanf-e commented on frontend/src/libs/components/confirm-article-delete-dialog/confirm-article-delete-dialog.tsx
> +    handleToggleModalOpen: () => void;
Check **A9**

2023-09-19 09:30 UTC, andanf-e commented on frontend/src/libs/components/confirm-article-delete-dialog/confirm-article-delete-dialog.tsx
> +  }, [dispatch, id, hasRedirect]);
delete action should be passed from props
```suggestion

```

2023-09-19 12:42 UTC, andanf-e requested changes

2023-09-19 12:42 UTC, andanf-e commented on frontend/src/pages/libs/components/confirm-article-delete-dialog/confirm-article-delete-dialog.tsx
> +    onDeleteButtonClick: () => void;
I believe this should be `onToggleModalOpen`?

2023-09-19 13:17 UTC, andanf-e submitted a review, later dismissed

2023-09-19 16:52 UTC, hnoievets commented on frontend/src/pages/libs/components/confirm-article-delete-dialog/confirm-article-delete-dialog.tsx
> +    </>
```suggestion
    <Modal
      isOpen={isOpen}
      onClose={handleClose}
      className={styles.confirmModal}
    >
      <p className={styles.message}>
        Are you sure you want to delete this article? This action cannot be
        undone.
      </p>
      <div className={styles.buttonWrapper}>
        <Button
          type={ButtonType.BUTTON}
          label="Cancel"
          onClick={handleClose}
          className={styles.buttonCancel}
        />
        <Button
          type={ButtonType.BUTTON}
          label="Delete"
          onClick={onDeleteArticle}
          className={styles.buttonDelete}
        />
      </div>
    </Modal>
```
Because just a param `isOpen` equals to `isOpen={true}`, that's why you had to use `&&`

2023-09-19 18:12 UTC, andanf-e approved these changes

2023-09-20 06:57 UTC, WilhelmWesser approved these changes

2023-09-20 06:59 UTC, merged