wr-259: Add like and dislike buttons to article page
BinaryStudioAcademy/bsa-2023-writorium pull request #270
Opened 2023-09-19 06:20 UTC by kovAnya

2023-09-19 07:05 UTC, andanf-e requested changes

2023-09-19 07:05 UTC, andanf-e commented on frontend/src/pages/article/components/article-view/article-view.tsx
> +import { getReactionConvertedToBoolean } from '../../../articles/libs/helpers/helpers.js';
If helper is used for separate pages - it's better to move it to common helpers and use it for both, instead of importing it from other pages

2023-09-19 07:05 UTC, andanf-e commented on frontend/src/pages/article/components/article-view/article-view.tsx
> +  const { likesCount, dislikesCount, hasAlreadyReactedWith } = user?.id
If it's a check for shared view case - then let's check explicitly with isShared condition

2023-09-19 07:05 UTC, andanf-e commented on frontend/src/slices/articles/articles.slice.ts
> +        );
```suggestion
      if (state.article) {
        state.article = removeReactionFromState(
          state.article as ArticleWithCommentCountResponseDto,
          reactionId,
        );
      }
```

2023-09-19 07:05 UTC, andanf-e commented on frontend/src/slices/articles/libs/helpers/set-reaction-to-state.helper.ts
> +const setReactionToState = (
Let's call it `updateReaction`

2023-09-19 07:05 UTC, andanf-e commented on frontend/src/slices/articles/libs/helpers/remove-reaction-from-state.helper.ts
> +const removeReactionFromState = (
Let's call it `removeReaction`

2023-09-19 07:05 UTC, andanf-e commented on frontend/src/slices/articles/articles.slice.ts
> +
```suggestion
      if (state.article) {
        state.article = setReactionToState(
          state.article as ArticleWithCommentCountResponseDto,
          updatedReaction,
        );
      }
```

2023-09-19 15:09 UTC, andanf-e submitted a review, later dismissed

2023-09-20 07:18 UTC, WilhelmWesser submitted a review, later dismissed

2023-09-20 08:00 UTC, WilhelmWesser approved these changes

2023-09-20 08:23 UTC, andanf-e approved these changes

2023-09-20 09:02 UTC, merged