wr-259: Add handleIconClick
BinaryStudioAcademy/bsa-2023-writorium pull request #272
Opened 2023-09-19 07:46 UTC by kovAnya

2023-09-19 07:53 UTC, andanf-e commented on frontend/src/pages/article/components/article-view/article-view.tsx
> +  const handleCommentIconClick = useCallback(() => {
Can't we just replace IconButton on comments here with Link to `#comments`?

2023-09-19 12:23 UTC, andanf-e requested changes

2023-09-19 12:23 UTC, andanf-e commented on frontend/src/pages/article/components/article-view/article-view.tsx
> +              />
If it's a link for now - then you don't need to use IconButton - it could be just an Icon

2023-09-19 12:31 UTC, andanf-e commented on frontend/src/pages/article/components/article-view/article-view.tsx
> +              to={`#${LinkHash.COMMENTS}` as typeof AppRoute.ARTICLES_$ID}
Let's try it this way
```suggestion
              to={{ hash: LinkHash.COMMENTS }}
```

2023-09-19 13:31 UTC, andanf-e approved these changes, later dismissed

2023-09-20 07:58 UTC, WilhelmWesser approved these changes, later dismissed

2023-09-20 09:19 UTC, andanf-e approved these changes

2023-09-21 13:50 UTC, andanf-e approved these changes

2023-09-21 16:12 UTC, nickolay-grechkin approved these changes

2023-09-21 16:12 UTC, merged