wr-203:  Add achievements checking functionality
BinaryStudioAcademy/bsa-2023-writorium pull request #276
Opened 2023-09-19 14:25 UTC by hnoievets

**I implemented this task in another way.** 
In this branch I don't use `achievements` from the slice, and `ownAchievements` looks like this:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/90383315/fa5a379f-abaa-40f6-857b-0e49601235ae)

Because I believe, filtering user achievements during calculating progress, and then fetching those user achievements separately from a client side is unnecessary work, and I don't understand where to store `progress` on FE if we would have `state.achievements` - base achievements and `state.ownAchievements` - objects with: id, userId, and achievementId 😐

- [x] Create users_achievements (with schema provided from readme) table (user_id | achievement_id cols pair should be unique)
- [x]  Add 2 columns for achievements table (breakpoint with count of items to achieve it and reference_table with table name for referencing achievement)
- [x]  On saving Article call achievements service to check wether any achievement breakpoint was accomplished:
- If breakpoint is accomplished - then make record in users_achievements table
- [x]  On saving Comment - same way, but for comments table
- If breakpoint is accomplished - then make record in users_achievements table
- [x]  On user profile - fetch user achievements and show the actual ones
Also implemented calculating achievement progress.

![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/90383315/da3e0eab-a952-4193-8fdb-22243888d96a)

![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/90383315/14d9fc82-3760-4809-abbf-5da4a2445e76)

2023-09-19 18:11 UTC, andanf-e requested changes

2023-09-19 18:11 UTC, andanf-e commented on backend/src/db/migrations/20230913114720_add_breakpoint_and_reference_table_columns_to_achievements.ts
> +const DataToUpdate = [
As it's a constant
```suggestion
const DATA_TO_UPDATE = [
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/db/migrations/20230913114720_add_breakpoint_and_reference_table_columns_to_achievements.ts
> +  ACHEVEMENTS: 'achievements',
typo
```suggestion
  ACHIEVEMENTS: 'achievements',
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.entity.ts
> +  private 'referenceTable': string;
```suggestion
  private 'referenceTable': typeof DatabaseTableName.ARTICLES | typeof DatabaseTableName.COMMENTS;
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.model.ts
> +  public 'referenceTable': string;
```suggestion
  public 'referenceTable': typeof DatabaseTableName.ARTICLES | typeof DatabaseTableName.COMMENTS;
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.repository.ts
> +    filters: Partial<Achievement> = {},
As they are only ones used
```suggestion
    filters: Pick<Achievement, 'breakpoint' | 'referenceTable'>,
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.repository.ts
> +type referenceTableType = ValueOf<typeof DatabaseTableName>;
1. Types should be named with capitalized letter
2. If you're using in through app - then add it to common types
3. I believe we should restrict it with currently maintained reference tables (`DatabaseTableName.ARTICLES` and `DatabaseTableName.COMMENTS`)

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.repository.ts
> +      .groupBy('referenceTable')
```suggestion
      .distinctOn('referenceTable')
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.repository.ts
> +          .count(`* as ${referenceTable}`)
```suggestion
          .count('*', { as: referenceTable })
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.repository.ts
> +        const count = (await knex
```suggestion
        return knex
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.repository.ts
> +    return await Promise.all(
```suggestion
    const referenceTablesCounts =  await Promise.all(
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.repository.ts
> +    );
```suggestion
    );
    
    return referenceTablesCounts.reduce<Record<ReferenceTable, number>>((groupedCount, referenceTableToCount) => {
      const [[tableName, count]] = Object.entries(referenceTableToCount)
      return {
        ...groupedCount,
        [tableName]: Number(count)
      };
    }, {});
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.service.ts
> +    const counts = await this.achievementRepository.getCountsInReferenceTables(
```suggestion
    const referenceTableToCount = await this.achievementRepository.getCountsInReferenceTables(
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.service.ts
> +        : 0;
After changes with grouping in repository
```suggestion
      const countByAchievementReference = referenceTableToCount[achievement.referenceTable] ?? PercentageProgress.MIN;
```

2023-09-19 18:11 UTC, andanf-e commented on backend/src/packages/achievements/achievement.service.ts
> +      const progress = Math.round((count / achievement.breakpoint) * 100);
```suggestion
      const progress = Math.round((count / achievement.breakpoint) * PercentageProgress.MAX);
```

2023-09-19 18:11 UTC, andanf-e commented on frontend/src/pages/profile/components/user-achievements/user-achievements.tsx
> +            0,
**B31**

2023-09-19 18:11 UTC, andanf-e commented on readme.md
> +    text reference_table
```suggestion
    text reference_table "referencing to table with records for achievements"
```

2023-09-19 18:11 UTC, andanf-e commented
> **I implemented this task in another way.** In this branch I don't use `achievements` from the slice, and `ownAchievements` looks like this: ![image](https://user-images.githubusercontent.com/90383315/268976985-fa5a379f-abaa-40f6-857b-0e49601235ae.png)
> 
> Because I believe, filtering user achievements during calculating progress, and then fetching those user achievements separately from a client side is unnecessary work, and I don't understand where to store `progress` on FE if we would have `state.achievements` - base achievements and `state.ownAchievements` - objects with: id, userId, and achievementId 😐
> 
> * [x]  Create users_achievements (with schema provided from readme) table (user_id | achievement_id cols pair should be unique)
> * [x]   Add 2 columns for achievements table (breakpoint with count of items to achieve it and reference_table with table name for referencing achievement)
> * [x]   On saving Article call achievements service to check wether any achievement breakpoint was accomplished:
> * If breakpoint is accomplished - then make record in users_achievements table
> * [x]   On saving Comment - same way, but for comments table
> * If breakpoint is accomplished - then make record in users_achievements table
> * [x]   On user profile - fetch user achievements and show the actual ones
>   Also implemented calculating achievement progress.
> 
> ![image](https://user-images.githubusercontent.com/90383315/268975707-da3e0eab-a952-4193-8fdb-22243888d96a.png)
> 
> ![image](https://user-images.githubusercontent.com/90383315/268974902-14d9fc82-3760-4809-abbf-5da4a2445e76.png)

If so - then let's get rid of unused parts from slice

2023-09-20 10:21 UTC, hnoievets commented
I would also like to point out that achievements achieved before using the achievement check functionality are displayed incorrectly.

![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/90383315/3180ea08-9fc1-4421-9a88-18e72ae662c1)

2023-09-20 11:10 UTC, andanf-e commented
> I would also like to point out that achievements achieved before using the achievement check functionality are displayed incorrectly.
> 
> ![image](https://user-images.githubusercontent.com/90383315/269250685-3180ea08-9fc1-4421-9a88-18e72ae662c1.png)

Maybe then let's prepopulate user_achievements table with already achieved for users,
Or on checkAchievement - add greater-then check instead of equality

2023-09-20 11:54 UTC, hnoievets commented
> Maybe then let's prepopulate user_achievements table with already achieved for users, Or on checkAchievement - add greater-than check instead of equality

Can I fix it like here https://github.com/BinaryStudioAcademy/bsa-2023-writorium/pull/276/commits/183ddd83af32981ad32060de3c5566e4181846b5?

Or there is a possibility that they will add a new achievement that has already been achieved?

2023-09-20 16:51 UTC, andanf-e commented
> > Maybe then let's prepopulate user_achievements table with already achieved for users, Or on checkAchievement - add greater-than check instead of equality
> 
> Can I fix it like here [183ddd8](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/commit/183ddd83af32981ad32060de3c5566e4181846b5)?
> 
> Or is there a possibility that they will add a new achievement that has already been achieved?

This is only display workaround - we do need to have already achieved records in user_achievements table

2023-09-21 07:17 UTC, andanf-e commented on backend/src/db/migrations/20230920200620_record_achieved_achievements_in_users_achievements_table.ts
> +    }
Can we achieve this with raw sql

2023-09-21 07:33 UTC, hnoievets commented on backend/src/db/migrations/20230920200620_record_achieved_achievements_in_users_achievements_table.ts
> +    }
OK, I'll try

2023-09-21 16:17 UTC, nickolay-grechkin approved these changes, later dismissed

2023-09-22 13:30 UTC, andanf-e reviewed
Overall looks nice 👍

2023-09-22 13:30 UTC, andanf-e commented on backend/src/db/migrations/20230920200620_record_achieved_achievements_in_users_achievements_table.ts
> +    WITH UsersCounts AS (
As CTE is still structure like a table - let's call it as tables
```suggestion
    WITH user_counts AS (
```

2023-09-22 13:30 UTC, andanf-e commented on backend/src/db/migrations/20230920200620_record_achieved_achievements_in_users_achievements_table.ts
> +      ) t
Let's get rid of shortens, as with them it's hard to understand what table is actually being referenced 
```suggestion
      ) grouped_reference_tables_counts
```

2023-09-22 13:39 UTC, hnoievets commented on backend/src/db/migrations/20230920200620_record_achieved_achievements_in_users_achievements_table.ts
> +      ) t
Get rid of all the shortens?

2023-09-22 14:28 UTC, andanf-e approved these changes

2023-09-23 07:53 UTC, nickolay-grechkin approved these changes

2023-09-23 07:56 UTC, merged