wr-282: add filters to genre stars chart
BinaryStudioAcademy/bsa-2023-writorium pull request #295
Opened 2023-09-21 11:46 UTC by canterbery

![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/44391531/8cee9c5b-b97a-43ec-8597-e84c307502ef)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/44391531/ea6f4d15-0944-40fa-86f9-cb871fee0025)

2023-09-21 13:48 UTC, andanf-e requested changes

2023-09-21 13:48 UTC, andanf-e commented on backend/src/packages/articles/libs/helpers/get-article-pubished-status-query.helper.ts
> +      articleStatus === 'draft'
Let's create `ArticlePublishStatus` enum in shared and use it on backend\frontend
```suggestion
      articleStatus === ArticlePublishStatus.DRAFT
```

2023-09-21 13:48 UTC, andanf-e commented on backend/src/packages/users/user.controller.ts
> +            query: ArticleGenreStatsFilters;
Please add validation for query

2023-09-21 14:13 UTC, PablloZz commented on frontend/src/pages/profile/components/user-articles-genres-stats/user-articles-genres-stats.tsx
> +                  label=""
Maybe "Choose article genre" will be more descriptive?

2023-09-21 15:58 UTC, andanf-e approved these changes

2023-09-22 07:27 UTC, WilhelmWesser approved these changes

2023-09-22 07:32 UTC, merged