wr-305: Quality criteria fixes Pt. 2
BinaryStudioAcademy/bsa-2023-writorium pull request #334
Opened 2023-09-24 13:56 UTC by PablloZz

2023-09-24 15:07 UTC, andanf-e requested changes

2023-09-24 15:07 UTC, andanf-e commented on backend/src/db/migrations/20230821120000_create_user_details_table.ts
Let's keep already existing migrations as they are

2023-09-24 15:07 UTC, andanf-e commented on backend/src/db/migrations/20230906064951_update_genres_keys.ts
Let's keep already existing migrations as they are

2023-09-24 15:07 UTC, andanf-e commented on backend/src/libs/packages/config/config.package.ts
> +      ALGORITHM: AUTH_CONFIG_ALGORITHM,
Let's keep algorithm declaration here - it's config file and this value is used only here + key ALGORITHM says what this string means

2023-09-24 15:07 UTC, andanf-e commented on backend/src/libs/packages/google-auth-client/google-auth-client.package.ts
> +      POSTMESSAGE,
Keep this option as it was - it's a single value used for library option in a single place

2023-09-24 15:07 UTC, andanf-e commented on backend/src/packages/articles/libs/helpers/get-where-author-id-query.helper.ts
> +      void builder.where(ArticleColumn.USER_ID, authorId);
Move it back

2023-09-24 15:07 UTC, andanf-e commented on backend/src/packages/articles/libs/helpers/get-where-genre-id-query.helper.ts
> +      void builder.where(ArticleColumn.GENRE_ID, genreId);
Move it back

2023-09-24 15:07 UTC, andanf-e commented on backend/src/packages/articles/libs/helpers/get-where-title-like-query.helper.ts
> +      void builder.whereILike(ArticleColumn.TITLE, `%${titleFilter}%`);
Move it back

2023-09-24 15:07 UTC, andanf-e commented on backend/src/packages/articles/libs/helpers/get-where-user-id-query.helper.ts
> +      void builder.where(ArticleColumn.USER_ID, userId);
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/components/input/input.tsx
> +  placeholder = EMPTY_STRING,
Move back all things with EMPTY_STRING to `''`

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/components/popover/popover.tsx
> +      role={ButtonType.BUTTON}
Move it back that's a value from union type
And that's not a button type, that's a aria role
<img width="524" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/ab888470-48a8-4be7-b4cf-c9c1f12cf29f">

2023-09-24 15:07 UTC, andanf-e commented on shared/src/libs/constants/empty-string.constant.ts
> +const EMPTY_STRING = '';
Turn back all places to have `''` instead of it
```suggestion
```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/slices/articles/actions.ts
> +      type: NotificationType.SUCCESS,
Move it back that's a union
<img width="336" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/d459fc25-6724-4d50-b5ed-cdfdeb7fd798">

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/slices/articles/actions.ts
> +  const sharingNotifyMessage = 'The sharing link was copied to clipboard';
Or move it back to message, or name it as constant

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/slices/auth/actions.ts
> +        type: NotificationType.SUCCESS,
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/slices/auth/actions.ts
> +    const resetPasswordEmailMessage =
Move it back to message prop or name it as constant

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/slices/auth/actions.ts
> +import { NotificationType } from '~/packages/notification/notification.js';
```suggestion

```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/packages/notification/libs/constants/error-message.constant.ts
> +const INFO_MESSAGE = 'Info!';
Move it back into default value string, or place in enum

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/article/components/article-form/libs/components/article-cover-upload/article-cover-upload.tsx
> +          appActions.notify({ type: ERROR_TYPE, message: error.message });
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/article/components/article-form/libs/components/article-cover-upload/article-cover-upload.tsx
> +              type={InputType.FILE}
That's a union, move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/article/components/article-form/libs/constants/error-type.constant.ts
> +const ERROR_TYPE = 'error';
```suggestion
```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/article/components/article-details/article-details.tsx
> +                  : DRAFT_STATUS}
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/article/libs/constants/draft-status.constant.ts
> +const DRAFT_STATUS = 'draft';
```suggestion
```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/packages/notification/notification.package.ts
> +    position = DEFAULT_NOTIFICATION_POSITION,
Move it back, that's a union
<img width="231" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/40fe7eb6-d921-46a3-b9b5-0a73caa879b7">

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/packages/notification/notification.package.ts
> +      type: NotificationType.ERROR,
Move it back, that's a union 
<img width="229" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/5c702699-5dc3-4f2d-bcf6-ae3cf574d30c">

Same for other methods

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/packages/notification/libs/enums/notification-type.enum.ts
> +export { NotificationType };
```suggestion

```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/packages/notification/libs/constants/default-notification-position.constant.ts
> +const DEFAULT_NOTIFICATION_POSITION = 'top-right';
```suggestion
```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/auth/components/auth-submit-button/auth-submit-button.tsx
> +      type={ButtonType.SUBMIT}
Move it back, that's a union
<img width="230" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/a449a1aa-099c-445c-a0fb-e2d68a95c9a3">

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/article/libs/enums/scroll-into-view-value.enum.ts
> +export { ScrollIntoViewValue };
It's not needed - options are provided from union types
```suggestion

```
<img width="219" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/98de9efa-e37a-498e-bd1c-19c1db791091">
<img width="285" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/0785b0ab-ed38-4a0c-91cb-0f6a96bb1426">

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/auth/components/facebook-login-button/facebook-login-button.tsx
> +      const response = await api.login({ scope: EMAIL_STRING });
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/auth/components/facebook-login-button/facebook-login-button.tsx
> +        fields: [EMAIL_STRING],
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/auth/components/facebook-login-button/facebook-login-button.tsx
> +      type={ButtonType.BUTTON}
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/auth/components/facebook-login-button/libs/constants/email-string.constant.ts
> +export { EMAIL_STRING };
```suggestion

```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/auth/components/forgot-password-form/forgot-password-form.tsx
> +              type={InputType.EMAIL}
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/auth/components/password-input/password-input.tsx
> +        type={isPasswordVisible ? InputType.TEXT : InputType.PASSWORD}
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/auth/components/reset-password-form/reset-password-form.tsx
> +              type={InputType.PASSWORD}
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +              type={InputType.EMAIL}
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/auth/components/sign-up-form/sign-up-form.tsx
> +              type={InputType.TEXT}
Move it all back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/profile/components/avatar-wrapper/avatar-wrapper.tsx
> +          type={InputType.FILE}
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/pages/profile/components/user-articles-genres-stats/libs/constants/article-status-select-options.constant.ts
> +import { makeFirstLettersCapitalized } from '~/libs/helpers/helpers.js';
Move it back
```suggestion

```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/helpers/make-first-letters-capitalized/make-first-letters-capitalized.helper.ts
> +export { makeFirstLettersCapitalized };
We don't need this
```suggestion

```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/helpers/get-first-letters/get-first-letters.helper.ts
> +    .join(EMPTY_STRING);
```suggestion
    .join('');
```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/helpers/get-first-letters/get-first-letters.helper.ts
> +    .split(ONE_SPACE_DELIMITER)
In this case it's more clear to understand explicitly what is used as delimeter,, then to search for a constant to find out what does it mean
```suggestion
    .split(' ')
```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/helpers/get-first-letters/get-first-letters.helper.ts
> +    .map((word) => word.charAt(ZERO_COUNT))
```suggestion
    .map((word) => word.charAt(FIRST_ELEMENT_ARRAY_INDEX))
```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/constants/supported-file-types-string.constant.ts
> +  COMMA_SPACE_DELIMITER,
```suggestion
  ', '
```

2023-09-24 15:07 UTC, andanf-e commented on shared/src/libs/constants/comma-space-delimiter.constant.ts
> +export { COMMA_SPACE_DELIMITER };
```suggestion

```

2023-09-24 15:07 UTC, andanf-e commented on shared/src/libs/constants/one-space-delimiter.constant.ts
> +export { ONE_SPACE_DELIMITER };
```suggestion

```

2023-09-24 15:07 UTC, andanf-e commented on shared/src/libs/constants/first-index.constant.ts
> +const FIRST_INDEX = 1;
What should it mean?

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/components/tooltip/element-with-tooltip.tsx
> +        [DataTooltipKey.POSITION_STRATEGY]: tooltipPositionStrategy,
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/components/tooltip/element-with-tooltip.tsx
> +    : DataTooltipKey.HTML;
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/components/tooltip/element-with-tooltip.tsx
> +import { DataTooltipKey } from './libs/enums/enums.js';
```suggestion

```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/components/toggle-checkbox/toggle-checkbox.tsx
> +        type={InputType.CHECKBOX}
Move it back

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/components/text-editor/libs/extensions/font-size/libs/types/optional-string.type.ts
> +export { type OptionalString };
```suggestion

```

2023-09-24 15:07 UTC, andanf-e commented on frontend/src/libs/components/select/select.tsx
> +  placeholder = DEFAULT_SELECT_PLACEHOLDER,
Move it back

2023-09-24 15:07 UTC, andanf-e commented on backend/src/packages/articles/libs/enums/article-column.enum.ts
> +export { ArticleColumn };
```suggestion

```

2023-09-24 15:07 UTC, andanf-e commented on backend/src/packages/article-views/article-view.repository.ts
> +      .onConflict(CONFLICT_COLUMNS)
In this case it's not necessary - move it back

2023-09-25 05:53 UTC, PablloZz commented
@andanf-e should I replace all the uses of the Icon/Button Type or only in those places I edited in this PR?
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/84803938/05883798-8fde-48eb-88b8-2a9851d89b6d)

2023-09-25 06:13 UTC, PablloZz commented
@andanf-e I wonder, what difference is between an empty string and zero number, aren't they the same thing? Why should zero be moved to the constant and '' or ' ' not?

2023-09-25 07:13 UTC, andanf-e commented
> @andanf-e I wonder, what difference is between an empty string and zero number, aren't they the same thing? Why should zero be moved to the constant and '' or ' ' not?

On zero number - I also have complaints 🥲

2023-09-25 07:35 UTC, andanf-e requested changes

2023-09-25 07:35 UTC, andanf-e commented on backend/src/db/migrations/20230906064951_update_genres_keys.ts
> -
Let's keep this file unchanged

2023-09-25 07:35 UTC, andanf-e commented on backend/src/libs/constants/constants.ts
> +  ZERO_COUNT,
```suggestion

```

2023-09-25 07:35 UTC, andanf-e commented on backend/src/packages/articles/article.repository.ts
> +      viewCount: ZERO_COUNT,
Move it back - EMPTY_COMMENT \ EMPTY_VIEW is more informative

2023-09-25 07:35 UTC, andanf-e commented on shared/src/libs/constants/zero-count.constant.ts
> +export { ZERO_COUNT };
```suggestion
```

2023-09-25 07:35 UTC, andanf-e commented on shared/src/libs/constants/zero-count.constant.ts
> +export { ZERO_COUNT };
This is too general and in entity context means nothing

2023-09-25 07:35 UTC, andanf-e commented on frontend/src/slices/articles/libs/helpers/remove-reaction.helper.ts
> +  reactionsToUpdate.splice(reactionIndex, FIRST_ARRAY_ITEM_INDEX);
In this case it's ELEMENT_TO_REMOVE_COUNT

2023-09-25 07:35 UTC, andanf-e commented on frontend/src/pages/profile/components/user-articles-genres-stats/libs/helpers/normalize-genres-stats.helper.ts
> +  const mainGenres = sortedData.slice(ZERO_COUNT, maxGenres);
```suggestion
  const mainGenres = sortedData.slice(FIRST_ELEMENT_ARRAY_INDEX, maxGenres);
```

2023-09-25 07:35 UTC, andanf-e commented on frontend/src/pages/profile/components/user-articles-genres-stats/libs/helpers/normalize-genres-stats.helper.ts
> +              ZERO_COUNT,
```suggestion

```

2023-09-25 07:35 UTC, andanf-e commented on frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +    paginationParameters.current.skip = ZERO_COUNT;
Move it back

2023-09-25 07:35 UTC, andanf-e commented on frontend/src/libs/hooks/use-mouse-position/use-mouse-position.hook.ts
> +    y: ZERO_COUNT,
Move it back

2023-09-25 07:35 UTC, andanf-e commented on frontend/src/libs/helpers/get-reactions-info/get-reactions-info.helper.ts
> +      dislikesCount: ZERO_COUNT,
Move it back

2023-09-25 07:35 UTC, andanf-e commented on backend/src/packages/articles/libs/helpers/get-article-published-status-query.helper.ts
> +        : void builder.whereNotNull(ArticleSortingKey.PUBLISHED);
Move it back - currently it looks like you're filtering by sorting keys

2023-09-25 07:35 UTC, andanf-e commented on backend/src/packages/articles/article.service.ts
> +      READ_TIME_KEY in readTimeData &&
Move it back - it means the same as you've moved it to constant few lines above

2023-09-25 07:35 UTC, andanf-e commented on backend/src/packages/articles/article.service.ts
> +    const FIRST_ITEM_INDEX = 0;
I saw FIRST_ELEMENT_ARRAY_INDEX constant somewhere - can you use it here?

2023-09-25 10:58 UTC, andanf-e approved these changes, later dismissed

2023-09-25 12:41 UTC, andanf-e approved these changes

2023-09-25 12:41 UTC, merged