Task/wr 7 sign up be
BinaryStudioAcademy/bsa-2023-writorium pull request #37
Opened 2023-08-22 13:21 UTC by kovAnya

I have a conflict in package-lock.json. Didn't touch it, because I'm not sure how to fix it correctly.

2023-08-22 13:26 UTC, nickolay-grechkin commented
Conflicts in package-lock.json appear because someone's pr has been merged where new dependencies have been added.
You can accept the incoming changes and it will be correct.

2023-08-22 13:38 UTC, WilhelmWesser commented on backend/src/db/migrations/20230821120000_create_user_details_table.ts
> +    //   .inTable('files');
It is better to remove comments in code you submit for pr as this code is, actually unused and it pollutes file

2023-08-22 13:50 UTC, andanf-e requested changes

2023-08-22 13:50 UTC, andanf-e commented on backend/src/db/migrations/20230821120000_create_user_details_table.ts
Remove comments - we would add avatar_id when we need it

2023-08-22 13:50 UTC, andanf-e commented on backend/src/packages/users/user-details.model.ts
> +          to: `${DatabaseTableName.USERS}.user_id`,
It will be snake_cased by knex
```suggestion
          to: `${DatabaseTableName.USERS}.userId`,
```

2023-08-22 13:50 UTC, andanf-e commented on backend/src/packages/users/user-details.repository.ts
There should be not user-details repository - user_details is a subpart of user -- upon user creation you may just call insertion with `insertGraph` and pass userDetails part to it - same with joining this data from user_details to user - you may just use `withGraphJoined|Fetched`

2023-08-22 13:50 UTC, andanf-e commented on backend/src/packages/users/user.model.ts
> +          to: `${DatabaseTableName.USER_DETAILS}.user_id`,
```suggestion
          to: `${DatabaseTableName.USER_DETAILS}.userId`,
```

2023-08-22 13:50 UTC, andanf-e commented on backend/src/packages/users/user.service.ts
> +    userDetailsRepository: UserDetailsRepository;
```suggestion

```

2023-08-22 13:50 UTC, andanf-e commented on backend/src/packages/users/user.service.ts
> +    return { ...user.toObject(), firstName, lastName };
All user data should be processed through user entity
```suggestion
    return user.toObject();
```

2023-08-22 13:50 UTC, andanf-e commented on backend/src/packages/users/user-details.entity.ts
This entity is not needed - it's a firstName/lastName should be joined to user object by user entity

2023-08-22 13:50 UTC, andanf-e commented on backend/src/packages/users/user.service.ts
> +    const hashedPassword = await bcrypt.hash(payload.password, salt);
Create separate Encrypt package and use it here + add password salt rounds to config.ENCRYPTION
```suggestion
    const passwordSalt = await this.encrypt.generateSalt(
      this.config.ENCRYPTION.USER_PASSWORD_SALT_ROUNDS,
    );
    const hashedPassword = await this.encrypt.encrypt(
      payload.password,
      passwordSalt,
    );
```

2023-08-22 17:22 UTC, nickolay-grechkin requested changes

2023-08-22 17:22 UTC, nickolay-grechkin commented on backend/src/db/migrations/20230821120000_create_user_details_table.ts
> +const ColumnName = {
Add empty space before ColumName.

2023-08-22 17:22 UTC, nickolay-grechkin commented on backend/src/packages/users/users.ts
> +const userService = new UserService({ userRepository, userDetailsRepository });
After removing userDetailsRepository as @andanf-e suggested, don't forget to made UserService constructor get not object, but single argument - userRepository.

2023-08-22 17:22 UTC, nickolay-grechkin commented on backend/src/packages/users/users.ts
> +const userDetailsRepository = new UserDetailsRepository(UserDetailsModel);
```suggestion

```

2023-08-22 17:23 UTC, nickolay-grechkin commented
Don't forget to name pr properly.

2023-08-23 07:41 UTC, kovAnya commented on backend/src/packages/users/user-details.repository.ts
I've removed user-details entity and repository and moved user-details insertion to user creation. But I had errors with ts types while using insertGraph. Couldn't resolve them, so I just used both models in user.repository. Is this a mistake?

2023-08-23 08:27 UTC, andanf-e requested changes

2023-08-23 08:27 UTC, andanf-e commented on backend/src/db/migrations/20230821120000_create_user_details_table.ts
> +      .integer(ColumnName.USER_ID)
I guess it should be also not nullable

2023-08-23 08:27 UTC, andanf-e commented on backend/src/libs/packages/config/libs/types/environment-schema.type.ts
> +  };
We actually don't need it env - just declared in config
```suggestion

```

2023-08-23 08:27 UTC, andanf-e commented on backend/.env.example
> +USER_PASSWORD_SALT_ROUNDS=10
We don't need it in env - just declared in config
```suggestion

```

2023-08-23 08:27 UTC, andanf-e commented on backend/src/libs/packages/config/config.package.ts
> +      },
Instead of getting it from env - make method to get encryption config
 ```
 private get encryptionConfig(): EncryptConfig {
    return {
      USER_PASSWORD_SALT_ROUNDS: 10,
    };
  }
  ```
  and define in `constructor` values for ENCRYPTION
  ```
    this.ENCRYPTION = this.encryptionConfig;
  ```

```suggestion
      
```

2023-08-23 08:27 UTC, andanf-e commented on backend/src/libs/packages/encryption/encrypt.package.ts
> +import bcrypt from 'bcrypt';
```suggestion
import { genSalt, hash } from 'bcrypt';
```

2023-08-23 08:27 UTC, andanf-e commented on backend/src/libs/packages/encryption/encrypt.package.ts
> +class Encrypt {
```suggestion
class Encrypt implements IEncrypt {
```

2023-08-23 08:27 UTC, andanf-e commented on backend/src/packages/users/user.model.ts
> +import { Model } from 'objection';
```suggestion
import { type RelationMappings, Model } from 'objection';
```

2023-08-23 08:27 UTC, andanf-e commented on backend/src/packages/users/user.model.ts
> +import { UserDetailsModel } from './users.js';
```suggestion
import { UserDetailsModel } from './user-details.model.js';
```

2023-08-23 08:27 UTC, andanf-e commented on backend/src/packages/users/user-details.model.ts
> +import { UserModel } from './users.js';
```suggestion
import { UserModel } from './user.model.js';
```

2023-08-23 08:27 UTC, andanf-e commented on backend/src/packages/users/user.repository.ts
>        .query()
You may insert userDetails joined to user like this
And declare this const value for user relation expression
```
private defaultRelationExpression = 'userDetails';
```

```suggestion
    const user = await this.userModel
      .query
      .insertGraphAndFetch({
        email,
        passwordSalt,
        passwordHash,
        userDetails: {
          firstName,
          lastName,
        },
      })
      .withGraphFetched(this.defaultRelationExpression)
      .execute();
```

2023-08-23 08:27 UTC, andanf-e commented on backend/src/packages/users/user.repository.ts
> +    return UserEntity.initialize({ ...item, firstName, lastName });
Then if you'd use `insertGraphAndFetch` for insertion - you may return entity like this
```suggestion
    return UserEntity.initialize({
      id: user.id,
      email: user.email,
      passwordHash: user.passwordHash,
      passwordSalt: user.passwordSalt,
      firstName: user.userDetails.firstName,
      lastName: user.userDetails.lastName
    });
```

2023-08-23 16:45 UTC, andanf-e requested changes

2023-08-23 16:45 UTC, andanf-e commented on backend/src/db/migrations/20230821120000_create_user_details_table.ts
> +    table.increments();
Define `id` col explicitly
```suggestion
   table.increments(ColumnName.ID).primary();
```

2023-08-23 16:45 UTC, andanf-e commented on backend/src/libs/packages/config/config.ts
> +const { ENCRYPTION } = config;
It should go together with config
```suggestion

```

2023-08-23 16:45 UTC, andanf-e commented on backend/src/libs/packages/config/config.ts
> +} from './libs/interfaces/interfaces.js';
```suggestion
export { config };
export {
  type IConfig,
} from './libs/interfaces/interfaces.js';
```

2023-08-23 16:45 UTC, andanf-e commented on backend/src/libs/packages/config/libs/interfaces/config.interface.ts
> +}
It should be `type`, and it should be declared in separate file

2023-08-23 16:45 UTC, andanf-e commented on backend/src/libs/packages/encryption/encrypt.package.ts
> +import { type IEncrypt } from '~/libs/packages/encryption/encrypt.js';
```suggestion
import { type IEncrypt } from './libs/intefaces/interfaces.js';
```

2023-08-23 16:45 UTC, andanf-e commented on backend/src/packages/users/user-details.model.ts
> +  } {
```suggestion
  public static get relationMappings(): RelationMappings {
```

2023-08-23 16:45 UTC, andanf-e commented on backend/src/packages/users/user.entity.ts
> +  }
Seems like it's not used - so we don't need it
```suggestion

```

2023-08-23 16:45 UTC, andanf-e commented on backend/src/packages/users/user.model.ts
> +  } {
```suggestion
  public static get relationMappings(): RelationMappings {
```

2023-08-23 16:45 UTC, andanf-e commented on backend/src/packages/users/user.service.ts
> +  private ENCRYPTION: EncryptConfig;
```suggestion
  private config: IConfig;
```

2023-08-23 16:45 UTC, andanf-e commented on backend/src/packages/users/user.service.ts
> +      this.ENCRYPTION.USER_PASSWORD_SALT_ROUNDS,
```suggestion
      this.config.ENCRYPTION.USER_PASSWORD_SALT_ROUNDS,
```

2023-08-23 16:45 UTC, andanf-e commented on backend/src/packages/users/users.ts
> +import { ENCRYPTION } from '~/libs/packages/config/config.js';
```suggestion
import { config } from '~/libs/packages/config/config.js';
```

2023-08-23 20:57 UTC, andanf-e requested changes

2023-08-23 20:57 UTC, andanf-e commented on backend/src/db/migrations/20230821120000_create_user_details_table.ts
> +    table.increments();
Comments should be resolved only in case if they were fixed

2023-08-23 20:57 UTC, andanf-e commented on backend/src/libs/packages/config/config.ts
> +const { ENCRYPTION } = config;
Comments should be resolved only in case if they were fixed

2023-08-23 20:57 UTC, andanf-e commented on backend/src/libs/packages/config/config.ts
> +} from './libs/interfaces/interfaces.js';
Comments should be resolved only in case if they were fixed

2023-08-23 20:57 UTC, andanf-e commented on backend/src/libs/packages/config/libs/interfaces/config.interface.ts
> +}
Comments should be resolved only in case if they were fixed

2023-08-23 20:57 UTC, andanf-e commented on backend/src/libs/packages/encryption/encrypt.package.ts
> +import { type IEncrypt } from '~/libs/packages/encryption/encrypt.js';
Comments should be resolved only in case if they were fixed

2023-08-23 20:57 UTC, andanf-e commented on backend/src/packages/users/user-details.model.ts
> +  } {
Comments should be resolved only in case if they were fixed

2023-08-23 20:57 UTC, andanf-e commented on backend/src/packages/users/user.entity.ts
> +  }
Comments should be resolved only in case if they were fixed

2023-08-23 20:57 UTC, andanf-e commented on backend/src/packages/users/user.model.ts
> +  } {
Comments should be resolved only in case if they were fixed

2023-08-23 20:57 UTC, andanf-e commented on backend/src/packages/users/user.service.ts
> +  private ENCRYPTION: EncryptConfig;
Comments should be resolved only in case if they were fixed

2023-08-23 20:57 UTC, andanf-e commented on backend/src/packages/users/user.service.ts
> +      this.ENCRYPTION.USER_PASSWORD_SALT_ROUNDS,
Comments should be resolved only in case if they were fixed

2023-08-23 20:57 UTC, andanf-e commented on backend/src/packages/users/users.ts
> +import { ENCRYPTION } from '~/libs/packages/config/config.js';
Comments should be resolved only in case if they were fixed

2023-08-23 21:13 UTC, kovAnya commented on backend/src/db/migrations/20230821120000_create_user_details_table.ts
> +    table.increments();
Okay, got it. I've fixed everything but resolved the comments before pushing.

2023-08-24 06:30 UTC, andanf-e requested changes

2023-08-24 06:30 UTC, andanf-e commented on backend/src/packages/users/user.service.ts
> +import { type IEncrypt } from '~/libs/packages/encryption/libs/interfaces/encrypt.interface.js';
Name folder the same way as it's file, and add needed interface to reexport
```suggestion
import { type IEncrypt } from '~/libs/packages/encrypt/encrypt.js';
```

2023-08-24 07:25 UTC, nickolay-grechkin requested changes

2023-08-24 07:25 UTC, nickolay-grechkin commented on backend/src/libs/packages/config/libs/types/encrypt-config.type.ts
> +interface EncryptConfig {
```suggestion
type EncryptConfig = {
```

2023-08-24 08:51 UTC, andanf-e requested changes

2023-08-24 08:51 UTC, andanf-e commented on backend/src/libs/packages/encrypt/encrypt.ts
> +export { type IEncrypt } from '~/libs/packages/encrypt/libs/interfaces/encrypt.interface.js';
```suggestion
export { type IEncrypt } from './libs/interfaces/interfaces.js';
```

2023-08-24 11:20 UTC, andanf-e approved these changes

2023-08-24 12:13 UTC, mhrechkin approved these changes

2023-08-24 12:42 UTC, merged