wr-15: Header component
BinaryStudioAcademy/bsa-2023-writorium pull request #38
Opened 2023-08-22 15:26 UTC by PablloZz

2023-08-22 15:48 UTC, andanf-e requested changes

2023-08-22 15:48 UTC, andanf-e commented on frontend/src/libs/components/avatar/avatar.tsx
> +  );
1 - link should not be in common Avatar url - other places won't need a link when using Avatar component -- wrap Avatar component with link in Header (where you need it)
2 - let's use early return for avatar placeholder
3 - there is getValidClassNames helper to join multiple classes assignment to nodes
```suggestion
  if (!avatarUrl) {
    return (
      <span className={getValidClassNames(styles.avatar, styles.defaultAvatar)}`}>
        <span className={styles.initials}>{getFirstLetters(username)}</span>
      </span>
    );
  }

  return <img src={avatarUrl} alt="avatar" className={styles.avatar} />;
```

2023-08-22 15:48 UTC, andanf-e commented on frontend/src/libs/components/header/header.tsx
> +import avatar from '~/assets/img/user-avatar.svg';
```suggestion

```

2023-08-22 15:48 UTC, andanf-e commented on frontend/src/libs/components/header/header.tsx
> +        <Avatar username="" avatarUrl={avatar} />
Let's place here some mocked user name for now
```suggestion
        <Avatar username="Todd Demoer" />
```

2023-08-22 15:48 UTC, andanf-e commented on frontend/src/libs/components/header/styles.module.scss
> +  padding: 30px 61px 31px 62px;
Let's use symmetric dimensions for padding 
```suggestion
  padding: 30px 60px;
```

2023-08-22 15:48 UTC, andanf-e commented on frontend/src/libs/components/header/styles.module.scss
> +  font-size: 20.463px;
```suggestion
  font-size: 20px;
```

2023-08-22 15:48 UTC, andanf-e commented on frontend/src/libs/components/header/styles.module.scss
> +  letter-spacing: 3.274px;
```suggestion
  letter-spacing: 3px;
```

2023-08-22 15:48 UTC, andanf-e commented on frontend/src/libs/helpers/get-first-letters/get-first-letters.ts
> +    .join('');
```suggestion
const getFirstLetters = (initialString: string): string => {
  return initialString
    .split(' ')
    .map((word) => word.charAt(0))
    .join('');
};
```

2023-08-22 16:01 UTC, artemmatiushenko1 commented on frontend/src/libs/components/avatar/styles.module.scss
> +.avatar-info {
I guess it would be better to stick to camel case like classnames instead of kebab case. Just as you did with `defaultAvatar`. So we don't need to use brackets when accessing the classnames in jsx

2023-08-22 16:03 UTC, andanf-e commented on frontend/src/libs/components/avatar/styles.module.scss
> +.avatar-info {
Yep, missed that 👍

2023-08-22 16:19 UTC, andanf-e requested changes

2023-08-22 16:19 UTC, andanf-e commented on frontend/src/libs/components/avatar/avatar.tsx
> +  avatarUrl?: string | null;
```suggestion
  avatarUrl: string | null;
```

2023-08-22 16:19 UTC, andanf-e commented on frontend/src/libs/components/header/header.tsx
> +          <Avatar username="Todd Demoer" />
Let's make it this way for now
```suggestion
          <Avatar username="Todd Demoer" avatarUrl={null} />
```

2023-08-22 16:19 UTC, andanf-e commented on frontend/src/assets/img/user-avatar.svg
remove it

2023-08-22 16:27 UTC, PablloZz commented on frontend/src/assets/img/user-avatar.svg
Removed optional chaining

2023-08-22 16:30 UTC, PablloZz commented on frontend/src/assets/img/user-avatar.svg
Removed optional parameter

2023-08-22 16:40 UTC, andanf-e requested changes

2023-08-22 16:40 UTC, andanf-e commented on frontend/src/assets/img/user-avatar.svg
Remove this image. We won't use it

2023-08-22 17:09 UTC, nickolay-grechkin requested changes

2023-08-22 17:09 UTC, nickolay-grechkin commented on frontend/src/libs/components/avatar/avatar.tsx
> +type Properties = {
It is a common practise to name this type - Props

2023-08-22 17:09 UTC, nickolay-grechkin commented on frontend/src/libs/components/header/header.tsx
> +type Properties = {
It is a common practise to name this type - Props

2023-08-22 17:26 UTC, nickolay-grechkin approved these changes, later dismissed

2023-08-23 05:37 UTC, PablloZz commented on frontend/src/assets/img/user-avatar.svg
Removed

2023-08-23 05:42 UTC, andanf-e submitted a review, later dismissed

2023-08-23 07:45 UTC, WilhelmWesser requested changes

2023-08-23 07:45 UTC, WilhelmWesser commented on frontend/src/libs/helpers/get-first-letters/get-first-letters.ts
> +const getFirstLetters = (initialString: string): string => {
Please, stick to naming convention for helpers like name.helper.ts

2023-08-23 12:00 UTC, andanf-e submitted a review, later dismissed

2023-08-23 14:33 UTC, andanf-e approved these changes

2023-08-23 14:38 UTC, nickolay-grechkin approved these changes

2023-08-23 14:40 UTC, WilhelmWesser approved these changes

2023-08-23 14:41 UTC, merged