wr-19: Loader Component
BinaryStudioAcademy/bsa-2023-writorium pull request #39
Opened 2023-08-22 15:38 UTC by hnoievets

Added Loader component that:

-  wraps component and shows loader upon `isLoading` prop;
- gets an optional `color` prop with a default value.

![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/90383315/f86c8b28-e731-47a3-9b9e-cbafb935580b)

2023-08-22 15:54 UTC, andanf-e requested changes

2023-08-22 15:54 UTC, andanf-e commented on frontend/src/libs/components/loader/enum/default-color.enum.ts
You don't need it

2023-08-22 15:54 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +        }}
```suggestion

```

2023-08-22 15:54 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +        className={styles.loader}
Better provide default color in styles and if we'd need to provide custom styles - then it would be provided by className from optional prop
```suggestion
        className={getValidClassNames(styles.loader, className)}
```

2023-08-22 15:54 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +  color?: string;
```suggestion
  className?: string;
```

2023-08-22 15:54 UTC, andanf-e commented on frontend/src/libs/components/loader/loader.tsx
> +  color = DefaultLoaderColor.BORDER,
```suggestion
  className,
```

2023-08-22 16:08 UTC, artemmatiushenko1 commented on frontend/src/libs/components/loader/loader.tsx
> +    return <>{children}</>;
Looks like fragment is unnecessary here. We can simply write `return children`

2023-08-22 17:05 UTC, nickolay-grechkin approved these changes, later dismissed

2023-08-22 18:51 UTC, andanf-e approved these changes

2023-08-23 10:33 UTC, WilhelmWesser approved these changes

2023-08-23 10:49 UTC, merged