wr-8: Sign Up | FE
BinaryStudioAcademy/bsa-2023-writorium pull request #45
Opened 2023-08-23 14:35 UTC by artemmatiushenko1

Implemented common layout for authorization pages. 

To display background letters I used just a text with a corresponding font. The reason I chose this aprroach is because the approach which is based on exporting all letters as transparent image and embedding it as backgound image doesn't produce the expected result and looks far too different from the design.

FYI @andanf-e, @WilhelmWesser, @nickolay-grechkin this pr doesn't contain the actual sign up form and validation schema because [wr-7](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/issues/7) and [wr-6](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/issues/6) blocking this task. Those features will be added as soon as blocking tickets are done.

2023-08-23 15:25 UTC, andanf-e requested changes

2023-08-23 15:25 UTC, andanf-e commented on frontend/src/pages/auth/auth.tsx
> +    />
Let's pass form element as children
```suggestion
    <AuthLayout>
      <>
        state: {dataStatus}
        {getScreen(pathname)}
      </>
    </AuthLayout>
```

2023-08-23 15:25 UTC, andanf-e commented on frontend/src/pages/auth/components/auth-layout/auth-layout.tsx
> +        key={item.value}
Using item value (which is letter), may lead to some unexpected behavior - as these letters may be the same (like duplicating W and R) and duplicate keys for elements may cause something bad with rendering

2023-08-23 15:25 UTC, andanf-e commented on frontend/src/pages/auth/components/auth-layout/libs/types/floating-letter.type.ts
> +    right?: number;
I believe they are not all optional,, but could exist in tuples, like
```
type Position = Record<'left' | 'top', number> | Record<'left' | 'bottom', number> | Record<'right' | 'top', number> | Record<'right'|'bottom', number>
```

2023-08-23 17:22 UTC, nickolay-grechkin approved these changes, later dismissed

2023-08-23 19:27 UTC, WilhelmWesser requested changes

2023-08-23 19:27 UTC, WilhelmWesser commented on frontend/src/pages/auth/components/auth-layout/auth-layout.tsx
> +        style={{ ...item.position }}
redundant destructurization as you pass nothing else there
```suggestion
        style={item.position}
```

2023-08-23 21:11 UTC, andanf-e submitted a review, later dismissed
LGTM, waiting for rest changes

2023-08-24 08:50 UTC, nickolay-grechkin approved these changes, later dismissed

2023-08-25 06:31 UTC, WilhelmWesser submitted a review, later dismissed

2023-08-25 21:37 UTC, drMangust commented
I believe it would be beneficial for us to explore the possibility of establishing a unified style for "background letters." This would enable us to ensure consistency and avoid the need for different implementations in various locations. Looking ahead, I'd like to suggest that openly discussing thoughts and ideas regarding specific implementations could lead to greater productivity. It appears that we have previously discussed these matters, but somehow a different decision was reached. Upon reflection, had an alternative implementation not been agreed upon, it could have resulted in your time being spent without purpose. I greatly value your innovative solution. However, considering the collaborative nature of our team, enhancing communication among us could prove even more invaluable.

2023-08-26 10:19 UTC, PablloZz commented on frontend/src/pages/auth/components/auth-layout/auth-layout.tsx
> +import styles from './styles.module.scss';
I think it should be exported from `'./libs/types/types.js';``

2023-08-26 10:21 UTC, PablloZz commented on frontend/src/pages/auth/components/auth-layout/auth-layout.tsx
> +import { type FloatingLetter } from './libs/types/floating-letter.type.js';
I think it should be exported from `'./libs/types/types.js';``

2023-08-27 07:19 UTC, andanf-e submitted a review, later dismissed

2023-08-27 09:07 UTC, b0bbobovich commented
After successfull registration you must add user token to localstorage. Add this logic to auth.actions.ts file.

2023-08-27 09:09 UTC, b0bbobovich commented
Also you need to modify validation scheme for sign-up in the shared folder to satisfy follow criterias: 
![Untitled](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/91199600/956ba63d-fa70-4052-a744-9ea5dc78b60c)

2023-08-27 10:29 UTC, andanf-e commented
> Also you need to modify validation scheme for sign-up in the shared folder to satisfy follow criterias: ![Untitled](https://user-images.githubusercontent.com/91199600/263518640-956ba63d-fa70-4052-a744-9ea5dc78b60c.png)

Let's merge basic functionality and extend it + setting user token to localStorage is a part of Auth Token ticket

2023-08-27 13:00 UTC, andanf-e approved these changes

2023-08-28 12:24 UTC, NazarKovtun1 approved these changes

2023-08-28 12:42 UTC, merged