wr-42: files uploading
BinaryStudioAcademy/bsa-2023-writorium pull request #58
Opened 2023-08-24 17:08 UTC by artemmatiushenko1

2023-08-25 10:31 UTC, andanf-e requested changes

2023-08-25 10:31 UTC, andanf-e commented on backend/src/libs/plugins/file-upload/libs/types/file-to-upload.type.ts
> +  extenstion: string;
```suggestion
  extension: string;
```

2023-08-25 10:31 UTC, andanf-e commented on backend/src/packages/files/file.controller.ts
> +        fileToUpload.extenstion,
```suggestion
        fileToUpload.extension,
```

2023-08-25 10:31 UTC, andanf-e commented on backend/src/libs/plugins/file-upload/file-upload.plugin.ts
> +          extenstion: getFileExtensionFromFileName(data.filename),
```suggestion
          extension: getFileExtensionFromFileName(data.filename),
```

2023-08-25 10:31 UTC, andanf-e commented on backend/src/libs/packages/file/libs/helpers/helpers.ts
Typo also in file name

2023-08-25 10:31 UTC, andanf-e commented on backend/src/libs/packages/file/libs/helpers/get-file-extenstion-from-filename.helper.ts
Type in file name `extension`

2023-08-25 10:31 UTC, andanf-e commented on backend/src/packages/files/file-upload-client.ts
> +    return 'file_' + Date.now().toString() + extension;
Use template string for concat

2023-08-25 16:16 UTC, andanf-e approved these changes, later dismissed

2023-08-26 09:27 UTC, artemmatiushenko1 commented
@andanf-e I've managed to move declaration merging to index.d.ts. I not sure how, but it currently works. Maybe it was a bug specifically on my machine

2023-08-27 13:19 UTC, andanf-e commented on backend/src/libs/packages/file/libs/constants/constants.ts
> +import { type ValueOf } from 'shared/build/index.js';
```suggestion
import { type ValueOf } from '~/libs/types/types.js';
```

2023-08-27 13:19 UTC, andanf-e commented on backend/src/libs/packages/file/libs/helpers/mb-to-bytes.helper.ts
> +const mbToBytes = (mb: number): number => {
```suggestion
const convertMbToBytes = (mb: number): number => {
```

2023-08-28 06:49 UTC, andanf-e requested changes

2023-08-28 06:49 UTC, andanf-e commented on backend/src/index.d.ts
> +    [FileUploadDecoratedPropety.FILE_TO_UPLOAD]: FileToUpload | null;
Typo
```suggestion
    [FileUploadDecoratedProperty.FILE_TO_UPLOAD]: FileToUpload | null;
```

2023-08-28 07:21 UTC, WilhelmWesser approved these changes, later dismissed

2023-08-29 06:35 UTC, merged