wr-57: Create common ErrorMessage Component
BinaryStudioAcademy/bsa-2023-writorium pull request #64
Opened 2023-08-26 08:02 UTC by AnastasiaR2

1. Component takes validation error prop and optional prop for custom styling. 
2. It has default styling that is relative to form field error styling. 
3. Applied to input and select components.

2023-08-26 08:46 UTC, andanf-e requested changes

2023-08-26 08:46 UTC, andanf-e commented on frontend/src/libs/components/select/select.tsx
> +      {hasError && <ErrorMessage error={error as string} />}
```suggestion
      <ErrorMessage error={error as string} />
```

2023-08-26 08:46 UTC, andanf-e commented on frontend/src/libs/components/input/styles.module.scss
> +  margin-bottom: 0;
```suggestion

```

2023-08-26 08:46 UTC, andanf-e commented on frontend/src/libs/components/input/styles.module.scss
> +  margin-bottom: 22px;
I believe you don't need this
```suggestion

```

2023-08-26 08:46 UTC, andanf-e commented on frontend/src/libs/components/input/input.tsx
> +      {hasError && <ErrorMessage error={error as string} />}
```suggestion
      <ErrorMessage error={error as string} />
```

2023-08-26 08:46 UTC, andanf-e commented on frontend/src/libs/components/error-message/error-message.tsx
> +  );
```suggestion
  const hasError = Boolean(error);

  return (
    <span className={getValidClassNames(styles.errorMessage, className)}>
      {hasError && error}
    </span>
  );
```

2023-08-26 08:46 UTC, andanf-e commented on frontend/src/libs/components/error-message/styles.module.scss
> +  color: var(--red);
```suggestion
  color: var(--red);
  min-height: <desired_height>
```

2023-08-28 07:41 UTC, andanf-e approved these changes

2023-08-28 15:46 UTC, WilhelmWesser approved these changes

2023-08-28 15:56 UTC, mhrechkin approved these changes

2023-08-28 15:59 UTC, merged