wr-74: Create achievements table
BinaryStudioAcademy/bsa-2023-writorium pull request #86
Opened 2023-08-29 07:05 UTC by AnastasiaR2

1. Created migration to add the achievements table.
2. Prepopulated achievements table with common achievements (write the first article, write 5/10/15/25/50 articles, same with comments).
3. Created achievements repository\service\controller.

2023-08-29 07:13 UTC, WilhelmWesser commented on backend/src/packages/achievements/achievement.entity.ts
> +  }: Omit<AchievementEntityType, 'id'>): AchievementEntity {
I offer move this omit to separate type

type AchievementEntityPayloadType = Omit<AchievementEntityType, 'id'>
```suggestion
  }: AchievementEntityPayloadType): AchievementEntity {
```

2023-08-29 07:13 UTC, WilhelmWesser commented on backend/src/packages/achievements/achievement.entity.ts
> +  }: Omit<AchievementEntityType, 'id'>): AchievementEntity {
Move this type before AchievmentEntity class but after imports

2023-08-29 12:01 UTC, andanf-e requested changes

2023-08-29 12:01 UTC, andanf-e commented on backend/package.json
> +    "seed:dev": "node --loader ts-paths-esm-loader ../node_modules/knex/bin/cli.js seed:run",
We don't need it
```suggestion

```

2023-08-29 12:01 UTC, andanf-e commented on backend/src/db/seeds/achievements-seed.ts
We don't need it

2023-08-29 12:01 UTC, andanf-e commented on backend/src/libs/packages/database/database.package.ts
> +      },
Move data prepopulation to `migrations`
```suggestion

```

2023-08-29 16:39 UTC, andanf-e approved these changes, later dismissed

2023-08-29 16:43 UTC, nickolay-grechkin approved these changes, later dismissed

2023-08-30 06:58 UTC, WilhelmWesser approved these changes, later dismissed

2023-08-30 09:30 UTC, andanf-e requested changes

2023-08-30 09:30 UTC, andanf-e commented on shared/src/packages/achievements/libs/types/achievement-entity.type.ts
> +type AchievementEntityType = {
type naming should not contain Type word itself

2023-08-30 18:31 UTC, andanf-e approved these changes

2023-08-31 13:13 UTC, NazarKovtun1 approved these changes

2023-08-31 13:16 UTC, merged