wr-82: Attach authorized user to the header
BinaryStudioAcademy/bsa-2023-writorium pull request #98
Opened 2023-08-30 05:45 UTC by PablloZz

2023-08-30 06:36 UTC, andanf-e requested changes

2023-08-30 06:36 UTC, andanf-e commented on frontend/src/libs/components/app/app.tsx
> +        {hasUser && <Header user={user} />}
I believe it's not necessary if we have separate check that user exists inside header component
So lets deal with a single approach - we are checking if user exists here OR inside header component (not in both places)

2023-08-30 06:36 UTC, andanf-e commented on frontend/src/libs/components/header/header.tsx
> +  user: UserAuthResponseDto | null;
We're now having real user from store - pass his own data to header instead of placeholder `username`

2023-08-30 13:55 UTC, andanf-e approved these changes

2023-08-31 05:55 UTC, nickolay-grechkin approved these changes

2023-08-31 06:17 UTC, merged